/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: Frontend/SpyserverDevice/SpyserverDevice.i

#ifndef SWIG_SpyserverDevice_WRAP_H_
#define SWIG_SpyserverDevice_WRAP_H_

class Swig_memory;

class SwigDirector_SpyserverDeviceCallback : public GoDeviceCallback
{
 public:
  SwigDirector_SpyserverDeviceCallback(int swig_p);
  void _swig_upcall_cbFloatIQ(void *data, int length) {
    GoDeviceCallback::cbFloatIQ(data,length);
  }
  virtual void cbFloatIQ(void *data, int length);
  void _swig_upcall_cbS16IQ(void *data, int length) {
    GoDeviceCallback::cbS16IQ(data,length);
  }
  virtual void cbS16IQ(void *data, int length);
  void _swig_upcall_cbS8IQ(void *data, int length) {
    GoDeviceCallback::cbS8IQ(data,length);
  }
  virtual void cbS8IQ(void *data, int length);
  virtual ~SwigDirector_SpyserverDeviceCallback();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
