/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: Frontend/SpyserverDevice/SpyserverDevice.i

package SpyserverDevice

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo CXXFLAGS: -std=c++11
#cgo LDFLAGS: -lSatHelper

typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
extern void _wrap_Swig_free_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_SpyserverDevice_62588b4ce09e2d9c(swig_intgo arg1);
extern swig_intgo _wrap_logERROR_SpyserverDevice_62588b4ce09e2d9c(void);
extern swig_intgo _wrap_logWARN_SpyserverDevice_62588b4ce09e2d9c(void);
extern swig_intgo _wrap_logINFO_SpyserverDevice_62588b4ce09e2d9c(void);
extern swig_intgo _wrap_logDEBUG_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap__swig_NewDirectorSpyserverDeviceCallbackSpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(int);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbFloatIQ_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, uintptr_t data, swig_intgo length);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbS16IQ_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, uintptr_t data, swig_intgo length);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbS8IQ_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, uintptr_t data, swig_intgo length);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_Info_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, swig_type_1 arg0);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_Error_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, swig_type_2 arg0);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_Warn_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, swig_type_3 arg0);
extern void _wrap__swig_DirectorSpyserverDeviceCallback_upcall_Debug_SpyserverDevice_62588b4ce09e2d9c(uintptr_t, swig_type_4 arg0);
extern void _wrap_DeleteDirectorSpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDeviceCallback_cbFloatIQ_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern void _wrap_SpyserverDeviceCallback_cbS16IQ_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern void _wrap_SpyserverDeviceCallback_cbS8IQ_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern void _wrap_SpyserverDeviceCallback_Info_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_1 arg2);
extern void _wrap_SpyserverDeviceCallback_Error_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_2 arg2);
extern void _wrap_SpyserverDeviceCallback_Warn_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_3 arg2);
extern void _wrap_SpyserverDeviceCallback_Debug_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_4 arg2);
extern void _wrap_delete_SpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_new_SpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap_new_Log_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_Log_Get__SWIG_0_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_Log_Get__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_delete_Log_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_new_Vector32u__SWIG_0_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap_new_Vector32u__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(swig_type_5 arg1);
extern swig_type_6 _wrap_Vector32u_size_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_type_7 _wrap_Vector32u_capacity_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector32u_reserve_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_8 arg2);
extern _Bool _wrap_Vector32u_isEmpty_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector32u_clear_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector32u_add_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Vector32u_get_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Vector32u_set_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_delete_Vector32u_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_new_Vector32f__SWIG_0_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap_new_Vector32f__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(swig_type_9 arg1);
extern swig_type_10 _wrap_Vector32f_size_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_type_11 _wrap_Vector32f_capacity_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector32f_reserve_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_12 arg2);
extern _Bool _wrap_Vector32f_isEmpty_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector32f_clear_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector32f_add_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, float arg2);
extern float _wrap_Vector32f_get_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Vector32f_set_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2, float arg3);
extern void _wrap_delete_Vector32f_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_new_Vector16i__SWIG_0_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap_new_Vector16i__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(swig_type_13 arg1);
extern swig_type_14 _wrap_Vector16i_size_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_type_15 _wrap_Vector16i_capacity_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector16i_reserve_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_16 arg2);
extern _Bool _wrap_Vector16i_isEmpty_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector16i_clear_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector16i_add_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, short arg2);
extern short _wrap_Vector16i_get_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Vector16i_set_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2, short arg3);
extern void _wrap_delete_Vector16i_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern uintptr_t _wrap_new_Vector8i__SWIG_0_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap_new_Vector8i__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(swig_type_17 arg1);
extern swig_type_18 _wrap_Vector8i_size_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_type_19 _wrap_Vector8i_capacity_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector8i_reserve_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_20 arg2);
extern _Bool _wrap_Vector8i_isEmpty_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector8i_clear_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_Vector8i_add_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, char arg2);
extern char _wrap_Vector8i_get_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Vector8i_set_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2, char arg3);
extern void _wrap_delete_Vector8i_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_intgo _wrap_AcquiringHeader_SpyserverDevice_62588b4ce09e2d9c(void);
extern swig_intgo _wrap_ReadingData_SpyserverDevice_62588b4ce09e2d9c(void);
extern swig_intgo _wrap_SAMPLE_BUFFER_SIZE_SpyserverDevice_62588b4ce09e2d9c(void);
extern uintptr_t _wrap_new_SpyserverDevice_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_type_21 arg2, swig_intgo arg3);
extern void _wrap_delete_SpyserverDevice_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_intgo _wrap_SpyserverDevice_SetSampleRate_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SpyserverDevice_SetCenterFrequency_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_SpyserverDevice_GetAvailableSampleRates_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_Start_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_Stop_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_SetAGC_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, _Bool arg2);
extern void _wrap_SpyserverDevice_SetLNAGain_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, char arg2);
extern void _wrap_SpyserverDevice_SetVGAGain_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, char arg2);
extern void _wrap_SpyserverDevice_SetMixerGain_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, char arg2);
extern void _wrap_SpyserverDevice_SetBiasT_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_SpyserverDevice_GetCenterFrequency_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_type_22 _wrap_SpyserverDevice_GetName_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern swig_intgo _wrap_SpyserverDevice_GetSampleRate_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_SetSamplesAvailableCallback_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_SpyserverDevice_Init_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_Destroy_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_Connect_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
extern void _wrap_SpyserverDevice_Disconnect_SpyserverDevice_62588b4ce09e2d9c(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_SpyserverDevice_62588b4ce09e2d9c(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const FRONTEND_SAMPLETYPE_FLOATIQ int = 0
const FRONTEND_SAMPLETYPE_S16IQ int = 1
const FRONTEND_SAMPLETYPE_S8IQ int = 2
type TLogLevel int
func _swig_getlogERROR() (_swig_ret TLogLevel) {
	var swig_r TLogLevel
	swig_r = (TLogLevel)(C._wrap_logERROR_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var LogERROR TLogLevel = _swig_getlogERROR()
func _swig_getlogWARN() (_swig_ret TLogLevel) {
	var swig_r TLogLevel
	swig_r = (TLogLevel)(C._wrap_logWARN_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var LogWARN TLogLevel = _swig_getlogWARN()
func _swig_getlogINFO() (_swig_ret TLogLevel) {
	var swig_r TLogLevel
	swig_r = (TLogLevel)(C._wrap_logINFO_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var LogINFO TLogLevel = _swig_getlogINFO()
func _swig_getlogDEBUG() (_swig_ret TLogLevel) {
	var swig_r TLogLevel
	swig_r = (TLogLevel)(C._wrap_logDEBUG_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var LogDEBUG TLogLevel = _swig_getlogDEBUG()
type _swig_DirectorSpyserverDeviceCallback struct {
	SwigcptrSpyserverDeviceCallback
	v interface{}
}

func (p *_swig_DirectorSpyserverDeviceCallback) Swigcptr() uintptr {
	return p.SwigcptrSpyserverDeviceCallback.Swigcptr()
}

func (p *_swig_DirectorSpyserverDeviceCallback) SwigIsSpyserverDeviceCallback() {
}

func (p *_swig_DirectorSpyserverDeviceCallback) DirectorInterface() interface{} {
	return p.v
}

func NewDirectorSpyserverDeviceCallback(v interface{}) SpyserverDeviceCallback {
	p := &_swig_DirectorSpyserverDeviceCallback{0, v}
	p.SwigcptrSpyserverDeviceCallback = SwigcptrSpyserverDeviceCallback(C._wrap__swig_NewDirectorSpyserverDeviceCallbackSpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(C.int(swigDirectorAdd(p))))
	return p
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackCbFloatIQ interface {
	CbFloatIQ(uintptr, int)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) CbFloatIQ(data uintptr, length int) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackCbFloatIQ); swig_ok {
		swig_g.CbFloatIQ(data, length)
		return
	}
	_swig_i_0 := data
	_swig_i_1 := length
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbFloatIQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DirectorSpyserverDeviceCallbackCbFloatIQ(p SpyserverDeviceCallback, arg2 uintptr, arg3 int) {
	_swig_i_0 := arg2
	_swig_i_1 := arg3
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbFloatIQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

//export Swig_DirectorSpyserverDeviceCallback_callback_cbFloatIQ_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_cbFloatIQ_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 uintptr, arg3 int) {
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
	swig_p.CbFloatIQ(arg2, arg3)
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackCbS16IQ interface {
	CbS16IQ(uintptr, int)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) CbS16IQ(data uintptr, length int) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackCbS16IQ); swig_ok {
		swig_g.CbS16IQ(data, length)
		return
	}
	_swig_i_0 := data
	_swig_i_1 := length
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbS16IQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DirectorSpyserverDeviceCallbackCbS16IQ(p SpyserverDeviceCallback, arg2 uintptr, arg3 int) {
	_swig_i_0 := arg2
	_swig_i_1 := arg3
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbS16IQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

//export Swig_DirectorSpyserverDeviceCallback_callback_cbS16IQ_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_cbS16IQ_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 uintptr, arg3 int) {
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
	swig_p.CbS16IQ(arg2, arg3)
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackCbS8IQ interface {
	CbS8IQ(uintptr, int)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) CbS8IQ(data uintptr, length int) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackCbS8IQ); swig_ok {
		swig_g.CbS8IQ(data, length)
		return
	}
	_swig_i_0 := data
	_swig_i_1 := length
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbS8IQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DirectorSpyserverDeviceCallbackCbS8IQ(p SpyserverDeviceCallback, arg2 uintptr, arg3 int) {
	_swig_i_0 := arg2
	_swig_i_1 := arg3
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_CbS8IQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

//export Swig_DirectorSpyserverDeviceCallback_callback_cbS8IQ_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_cbS8IQ_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 uintptr, arg3 int) {
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
	swig_p.CbS8IQ(arg2, arg3)
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackInfo interface {
	Info(string)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) Info(arg0 string) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackInfo); swig_ok {
		swig_g.Info(arg0)
		return
	}
	_swig_i_0 := arg0
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Info_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

func DirectorSpyserverDeviceCallbackInfo(p SpyserverDeviceCallback, arg2 string) {
	_swig_i_0 := arg2
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Info_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

//export Swig_DirectorSpyserverDeviceCallback_callback_Info_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_Info_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 string) {
	var _swig_i_0 string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
 _swig_i_0 = swigCopyString(arg2) 
	swig_p.Info(_swig_i_0)
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackError interface {
	Error(string)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) Error(arg0 string) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackError); swig_ok {
		swig_g.Error(arg0)
		return
	}
	_swig_i_0 := arg0
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Error_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

func DirectorSpyserverDeviceCallbackError(p SpyserverDeviceCallback, arg2 string) {
	_swig_i_0 := arg2
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Error_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

//export Swig_DirectorSpyserverDeviceCallback_callback_Error_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_Error_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 string) {
	var _swig_i_0 string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
 _swig_i_0 = swigCopyString(arg2) 
	swig_p.Error(_swig_i_0)
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackWarn interface {
	Warn(string)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) Warn(arg0 string) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackWarn); swig_ok {
		swig_g.Warn(arg0)
		return
	}
	_swig_i_0 := arg0
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Warn_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

func DirectorSpyserverDeviceCallbackWarn(p SpyserverDeviceCallback, arg2 string) {
	_swig_i_0 := arg2
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Warn_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

//export Swig_DirectorSpyserverDeviceCallback_callback_Warn_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_Warn_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 string) {
	var _swig_i_0 string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
 _swig_i_0 = swigCopyString(arg2) 
	swig_p.Warn(_swig_i_0)
}

type _swig_DirectorInterfaceSpyserverDeviceCallbackDebug interface {
	Debug(string)
}

func (swig_p *_swig_DirectorSpyserverDeviceCallback) Debug(arg0 string) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceSpyserverDeviceCallbackDebug); swig_ok {
		swig_g.Debug(arg0)
		return
	}
	_swig_i_0 := arg0
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Debug_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(swig_p.SwigcptrSpyserverDeviceCallback), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

func DirectorSpyserverDeviceCallbackDebug(p SpyserverDeviceCallback, arg2 string) {
	_swig_i_0 := arg2
	C._wrap__swig_DirectorSpyserverDeviceCallback_upcall_Debug_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(p.(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
}

//export Swig_DirectorSpyserverDeviceCallback_callback_Debug_SpyserverDevice_62588b4ce09e2d9c
func Swig_DirectorSpyserverDeviceCallback_callback_Debug_SpyserverDevice_62588b4ce09e2d9c(swig_c int, arg2 string) {
	var _swig_i_0 string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorSpyserverDeviceCallback)
 _swig_i_0 = swigCopyString(arg2) 
	swig_p.Debug(_swig_i_0)
}

func DeleteDirectorSpyserverDeviceCallback(arg1 SpyserverDeviceCallback) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_DeleteDirectorSpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

//export Swiggo_DeleteDirector_SpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c
func Swiggo_DeleteDirector_SpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(c int) {
	swigDirectorLookup(c).(*_swig_DirectorSpyserverDeviceCallback).SwigcptrSpyserverDeviceCallback = 0
	swigDirectorDelete(c)
}

type SwigcptrSpyserverDeviceCallback uintptr

func (p SwigcptrSpyserverDeviceCallback) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSpyserverDeviceCallback) SwigIsSpyserverDeviceCallback() {
}

func (p SwigcptrSpyserverDeviceCallback) DirectorInterface() interface{} {
	return nil
}

func (arg1 SwigcptrSpyserverDeviceCallback) CbFloatIQ(arg2 uintptr, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_SpyserverDeviceCallback_cbFloatIQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrSpyserverDeviceCallback) CbS16IQ(arg2 uintptr, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_SpyserverDeviceCallback_cbS16IQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrSpyserverDeviceCallback) CbS8IQ(arg2 uintptr, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_SpyserverDeviceCallback_cbS8IQ_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrSpyserverDeviceCallback) Info(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDeviceCallback_Info_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrSpyserverDeviceCallback) Error(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDeviceCallback_Error_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrSpyserverDeviceCallback) Warn(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDeviceCallback_Warn_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrSpyserverDeviceCallback) Debug(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDeviceCallback_Debug_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func DeleteSpyserverDeviceCallback(arg1 SpyserverDeviceCallback) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func NewSpyserverDeviceCallback() (_swig_ret SpyserverDeviceCallback) {
	var swig_r SpyserverDeviceCallback
	swig_r = (SpyserverDeviceCallback)(SwigcptrSpyserverDeviceCallback(C._wrap_new_SpyserverDeviceCallback_SpyserverDevice_62588b4ce09e2d9c()))
	return swig_r
}

type SpyserverDeviceCallback interface {
	Swigcptr() uintptr
	SwigIsSpyserverDeviceCallback()
	DirectorInterface() interface{}
	CbFloatIQ(arg2 uintptr, arg3 int)
	CbS16IQ(arg2 uintptr, arg3 int)
	CbS8IQ(arg2 uintptr, arg3 int)
	Info(arg2 string)
	Error(arg2 string)
	Warn(arg2 string)
	Debug(arg2 string)
}

type SwigcptrLog uintptr

func (p SwigcptrLog) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLog) SwigIsLog() {
}

func NewLog(arg1 SpyserverDeviceCallback) (_swig_ret Log) {
	var swig_r Log
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Log)(SwigcptrLog(C._wrap_new_Log_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrLog) Get__SWIG_0(arg2 TLogLevel) (_swig_ret Std_ostringstream) {
	var swig_r Std_ostringstream
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Std_ostringstream)(SwigcptrStd_ostringstream(C._wrap_Log_Get__SWIG_0_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrLog) Get__SWIG_1() (_swig_ret Std_ostringstream) {
	var swig_r Std_ostringstream
	_swig_i_0 := arg1
	swig_r = (Std_ostringstream)(SwigcptrStd_ostringstream(C._wrap_Log_Get__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrLog) Get(a ...interface{}) Std_ostringstream {
	argc := len(a)
	if argc == 0 {
		return p.Get__SWIG_1()
	}
	if argc == 1 {
		return p.Get__SWIG_0(a[0].(TLogLevel))
	}
	panic("No match for overloaded function call")
}

func DeleteLog(arg1 Log) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Log_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

type Log interface {
	Swigcptr() uintptr
	SwigIsLog()
	Get(a ...interface{}) Std_ostringstream
}

type SwigcptrVector32u uintptr

func (p SwigcptrVector32u) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVector32u) SwigIsVector32u() {
}

func NewVector32u__SWIG_0() (_swig_ret Vector32u) {
	var swig_r Vector32u
	swig_r = (Vector32u)(SwigcptrVector32u(C._wrap_new_Vector32u__SWIG_0_SpyserverDevice_62588b4ce09e2d9c()))
	return swig_r
}

func NewVector32u__SWIG_1(arg1 int64) (_swig_ret Vector32u) {
	var swig_r Vector32u
	_swig_i_0 := arg1
	swig_r = (Vector32u)(SwigcptrVector32u(C._wrap_new_Vector32u__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(C.swig_type_5(_swig_i_0))))
	return swig_r
}

func NewVector32u(a ...interface{}) Vector32u {
	argc := len(a)
	if argc == 0 {
		return NewVector32u__SWIG_0()
	}
	if argc == 1 {
		return NewVector32u__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrVector32u) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector32u_size_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector32u) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector32u_capacity_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector32u) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector32u_reserve_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrVector32u) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Vector32u_isEmpty_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector32u) Clear() {
	_swig_i_0 := arg1
	C._wrap_Vector32u_clear_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrVector32u) Add(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector32u_add_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrVector32u) Get(arg2 int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_Vector32u_get_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVector32u) Set(arg2 int, arg3 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Vector32u_set_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func DeleteVector32u(arg1 Vector32u) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Vector32u_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

type Vector32u interface {
	Swigcptr() uintptr
	SwigIsVector32u()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 uint)
	Get(arg2 int) (_swig_ret uint)
	Set(arg2 int, arg3 uint)
}

type SwigcptrVector32f uintptr

func (p SwigcptrVector32f) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVector32f) SwigIsVector32f() {
}

func NewVector32f__SWIG_0() (_swig_ret Vector32f) {
	var swig_r Vector32f
	swig_r = (Vector32f)(SwigcptrVector32f(C._wrap_new_Vector32f__SWIG_0_SpyserverDevice_62588b4ce09e2d9c()))
	return swig_r
}

func NewVector32f__SWIG_1(arg1 int64) (_swig_ret Vector32f) {
	var swig_r Vector32f
	_swig_i_0 := arg1
	swig_r = (Vector32f)(SwigcptrVector32f(C._wrap_new_Vector32f__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(C.swig_type_9(_swig_i_0))))
	return swig_r
}

func NewVector32f(a ...interface{}) Vector32f {
	argc := len(a)
	if argc == 0 {
		return NewVector32f__SWIG_0()
	}
	if argc == 1 {
		return NewVector32f__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrVector32f) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector32f_size_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector32f) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector32f_capacity_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector32f) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector32f_reserve_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_type_12(_swig_i_1))
}

func (arg1 SwigcptrVector32f) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Vector32f_isEmpty_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector32f) Clear() {
	_swig_i_0 := arg1
	C._wrap_Vector32f_clear_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrVector32f) Add(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector32f_add_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrVector32f) Get(arg2 int) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float32)(C._wrap_Vector32f_get_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVector32f) Set(arg2 int, arg3 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Vector32f_set_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.float(_swig_i_2))
}

func DeleteVector32f(arg1 Vector32f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Vector32f_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

type Vector32f interface {
	Swigcptr() uintptr
	SwigIsVector32f()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 float32)
	Get(arg2 int) (_swig_ret float32)
	Set(arg2 int, arg3 float32)
}

type SwigcptrVector16i uintptr

func (p SwigcptrVector16i) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVector16i) SwigIsVector16i() {
}

func NewVector16i__SWIG_0() (_swig_ret Vector16i) {
	var swig_r Vector16i
	swig_r = (Vector16i)(SwigcptrVector16i(C._wrap_new_Vector16i__SWIG_0_SpyserverDevice_62588b4ce09e2d9c()))
	return swig_r
}

func NewVector16i__SWIG_1(arg1 int64) (_swig_ret Vector16i) {
	var swig_r Vector16i
	_swig_i_0 := arg1
	swig_r = (Vector16i)(SwigcptrVector16i(C._wrap_new_Vector16i__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(C.swig_type_13(_swig_i_0))))
	return swig_r
}

func NewVector16i(a ...interface{}) Vector16i {
	argc := len(a)
	if argc == 0 {
		return NewVector16i__SWIG_0()
	}
	if argc == 1 {
		return NewVector16i__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrVector16i) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector16i_size_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector16i) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector16i_capacity_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector16i) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector16i_reserve_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1))
}

func (arg1 SwigcptrVector16i) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Vector16i_isEmpty_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector16i) Clear() {
	_swig_i_0 := arg1
	C._wrap_Vector16i_clear_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrVector16i) Add(arg2 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector16i_add_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrVector16i) Get(arg2 int) (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int16)(C._wrap_Vector16i_get_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVector16i) Set(arg2 int, arg3 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Vector16i_set_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.short(_swig_i_2))
}

func DeleteVector16i(arg1 Vector16i) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Vector16i_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

type Vector16i interface {
	Swigcptr() uintptr
	SwigIsVector16i()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int16)
	Get(arg2 int) (_swig_ret int16)
	Set(arg2 int, arg3 int16)
}

type SwigcptrVector8i uintptr

func (p SwigcptrVector8i) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVector8i) SwigIsVector8i() {
}

func NewVector8i__SWIG_0() (_swig_ret Vector8i) {
	var swig_r Vector8i
	swig_r = (Vector8i)(SwigcptrVector8i(C._wrap_new_Vector8i__SWIG_0_SpyserverDevice_62588b4ce09e2d9c()))
	return swig_r
}

func NewVector8i__SWIG_1(arg1 int64) (_swig_ret Vector8i) {
	var swig_r Vector8i
	_swig_i_0 := arg1
	swig_r = (Vector8i)(SwigcptrVector8i(C._wrap_new_Vector8i__SWIG_1_SpyserverDevice_62588b4ce09e2d9c(C.swig_type_17(_swig_i_0))))
	return swig_r
}

func NewVector8i(a ...interface{}) Vector8i {
	argc := len(a)
	if argc == 0 {
		return NewVector8i__SWIG_0()
	}
	if argc == 1 {
		return NewVector8i__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrVector8i) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector8i_size_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector8i) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Vector8i_capacity_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector8i) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector8i_reserve_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_type_20(_swig_i_1))
}

func (arg1 SwigcptrVector8i) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Vector8i_isEmpty_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVector8i) Clear() {
	_swig_i_0 := arg1
	C._wrap_Vector8i_clear_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrVector8i) Add(arg2 int8) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Vector8i_add_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrVector8i) Get(arg2 int) (_swig_ret int8) {
	var swig_r int8
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int8)(C._wrap_Vector8i_get_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVector8i) Set(arg2 int, arg3 int8) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Vector8i_set_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.char(_swig_i_2))
}

func DeleteVector8i(arg1 Vector8i) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Vector8i_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

type Vector8i interface {
	Swigcptr() uintptr
	SwigIsVector8i()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int8)
	Get(arg2 int) (_swig_ret int8)
	Set(arg2 int, arg3 int8)
}

type ParserPhase int
func _swig_getAcquiringHeader() (_swig_ret ParserPhase) {
	var swig_r ParserPhase
	swig_r = (ParserPhase)(C._wrap_AcquiringHeader_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var AcquiringHeader ParserPhase = _swig_getAcquiringHeader()
func _swig_getReadingData() (_swig_ret ParserPhase) {
	var swig_r ParserPhase
	swig_r = (ParserPhase)(C._wrap_ReadingData_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var ReadingData ParserPhase = _swig_getReadingData()
func _swig_getSAMPLE_BUFFER_SIZE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_SAMPLE_BUFFER_SIZE_SpyserverDevice_62588b4ce09e2d9c())
	return swig_r
}

var SAMPLE_BUFFER_SIZE int = _swig_getSAMPLE_BUFFER_SIZE()
type SwigcptrSpyserverDevice uintptr

func (p SwigcptrSpyserverDevice) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSpyserverDevice) SwigIsSpyserverDevice() {
}

func NewSpyserverDevice(arg1 SpyserverDeviceCallback, arg2 string, arg3 int) (_swig_ret SpyserverDevice) {
	var swig_r SpyserverDevice
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (SpyserverDevice)(SwigcptrSpyserverDevice(C._wrap_new_SpyserverDevice_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), *(*C.swig_type_21)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func DeleteSpyserverDevice(arg1 SpyserverDevice) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SpyserverDevice_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSpyserverDevice) SetSampleRate(arg2 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_SpyserverDevice_SetSampleRate_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpyserverDevice) SetCenterFrequency(arg2 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_SpyserverDevice_SetCenterFrequency_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpyserverDevice) GetAvailableSampleRates() (_swig_ret Vector32u) {
	var swig_r Vector32u
	_swig_i_0 := arg1
	swig_r = (Vector32u)(SwigcptrVector32u(C._wrap_SpyserverDevice_GetAvailableSampleRates_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSpyserverDevice) Start() {
	_swig_i_0 := arg1
	C._wrap_SpyserverDevice_Start_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSpyserverDevice) Stop() {
	_swig_i_0 := arg1
	C._wrap_SpyserverDevice_Stop_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSpyserverDevice) SetAGC(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDevice_SetAGC_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrSpyserverDevice) SetLNAGain(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDevice_SetLNAGain_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrSpyserverDevice) SetVGAGain(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDevice_SetVGAGain_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrSpyserverDevice) SetMixerGain(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDevice_SetMixerGain_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrSpyserverDevice) SetBiasT(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SpyserverDevice_SetBiasT_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrSpyserverDevice) GetCenterFrequency() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SpyserverDevice_GetCenterFrequency_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpyserverDevice) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_SpyserverDevice_GetName_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSpyserverDevice) GetSampleRate() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_SpyserverDevice_GetSampleRate_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpyserverDevice) SetSamplesAvailableCallback(arg2 SpyserverDeviceCallback) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_SpyserverDevice_SetSamplesAvailableCallback_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSpyserverDevice) Init() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_SpyserverDevice_Init_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpyserverDevice) Destroy() {
	_swig_i_0 := arg1
	C._wrap_SpyserverDevice_Destroy_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSpyserverDevice) Connect() {
	_swig_i_0 := arg1
	C._wrap_SpyserverDevice_Connect_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSpyserverDevice) Disconnect() {
	_swig_i_0 := arg1
	C._wrap_SpyserverDevice_Disconnect_SpyserverDevice_62588b4ce09e2d9c(C.uintptr_t(_swig_i_0))
}

type SpyserverDevice interface {
	Swigcptr() uintptr
	SwigIsSpyserverDevice()
	SetSampleRate(arg2 uint) (_swig_ret uint)
	SetCenterFrequency(arg2 uint) (_swig_ret uint)
	GetAvailableSampleRates() (_swig_ret Vector32u)
	Start()
	Stop()
	SetAGC(arg2 bool)
	SetLNAGain(arg2 byte)
	SetVGAGain(arg2 byte)
	SetMixerGain(arg2 byte)
	SetBiasT(arg2 byte)
	GetCenterFrequency() (_swig_ret uint)
	GetName() (_swig_ret string)
	GetSampleRate() (_swig_ret uint)
	SetSamplesAvailableCallback(arg2 SpyserverDeviceCallback)
	Init() (_swig_ret bool)
	Destroy()
	Connect()
	Disconnect()
}


type SwigcptrSwigDirector_SpyserverDeviceCallback uintptr
type SwigDirector_SpyserverDeviceCallback interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_SpyserverDeviceCallback) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_ostringstream uintptr
type Std_ostringstream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_ostringstream) Swigcptr() uintptr {
	return uintptr(p)
}



var swigDirectorTrack struct {
	sync.Mutex
	m map[int]interface{}
	c int
}

func swigDirectorAdd(v interface{}) int {
	swigDirectorTrack.Lock()
	defer swigDirectorTrack.Unlock()
	if swigDirectorTrack.m == nil {
		swigDirectorTrack.m = make(map[int]interface{})
	}
	swigDirectorTrack.c++
	ret := swigDirectorTrack.c
	swigDirectorTrack.m[ret] = v
	return ret
}

func swigDirectorLookup(c int) interface{} {
	swigDirectorTrack.Lock()
	defer swigDirectorTrack.Unlock()
	ret := swigDirectorTrack.m[c]
	if ret == nil {
		panic("C++ director pointer not found (possible	use-after-free)")
	}
	return ret
}

func swigDirectorDelete(c int) {
	swigDirectorTrack.Lock()
	defer swigDirectorTrack.Unlock()
	if swigDirectorTrack.m[c] == nil {
		if c > swigDirectorTrack.c {
			panic("C++ director pointer invalid (possible memory corruption")
		} else {
			panic("C++ director pointer not found (possible use-after-free)")
		}
	}
	delete(swigDirectorTrack.m, c)
}


