name: sathelperapp
version: git
version-script: cat version
summary: LRIT/HRIT Demodulator / Decoder
description: |
  The OpenSatelliteProject Satellite Helper Application! This is currently a LRIT/HRIT Demodulator / Decoder program

grade: stable
confinement: strict

apps:
  sathelperapp:
    plugs: [network-bind, network, home, raw-usb]
    command: SatHelperApp
  SatHelperApp: # Alias
    plugs: [network-bind, network, home, raw-usb]
    command: SatHelperApp
  DemuxReplay:
    command: DemuxReplay
  xritparse:
    command: xritparse
  xritcat:
    command: xritcat
  xritimg:
    command: xritimg
  xritpdcs:
    command: xritpdcs
  SatHelperDump:
    command: SatHelperDump
  SatHelperClient:
    plugs: [network-bind, network, home]
    command: SatHelperClient

parts:
  ppaadd:
    plugin: nil
    override-build: |
      echo "deb http://ppa.launchpad.net/opensatelliteproject/ppa/ubuntu xenial main" | tee /etc/apt/sources.list.d/opensatelliteproject.list
      echo "deb http://ppa.launchpad.net/opensatelliteproject/drivers/ubuntu xenial main" | tee /etc/apt/sources.list.d/drivers.list
      echo "deb http://ppa.launchpad.net/gophers/archive/ubuntu xenial main" | tee /etc/apt/sources.list.d/gophers-archive.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 496DD3727263A7A279F9B349407E8BB01C195687
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 11FC2E68126782B43762694F22C627172ECB91FE
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C73998DC9DFEA6DCF1241057308C15A29AD198E9
      apt update
      apt install -yy libaec-dev libaec0 libcorrect libsathelper libsoapysdr0.6 libairspy0 libsoapysdr-dev libairspy-dev git g++ cmake libsqlite3-dev libi2c-dev libusb-1.0-0-dev swig swig3.0 golang-1.11
      echo "Building RTLSDR"
      [ ! -d "librtlsdr" ] && git clone https://github.com/librtlsdr/librtlsdr.git
      cd librtlsdr && mkdir build && cd build && cmake .. && make -j10 && make install && ldconfig && cd ../..
      echo "Building Static LimeSuite"
      [ ! -d "LimeSuite" ] && git clone https://github.com/myriadrf/LimeSuite.git
      cd LimeSuite && git checkout stable && mkdir builddir && cd builddir && cmake ../ -DBUILD_SHARED_LIBS=OFF && make -j10 && make install && rm -fr * && cmake ../ && make -j10 && make install && ldconfig && cd ../..
    prime: [-*]

  sathelperapp:
    source: .
    plugin: make
    after: [ppaadd]
    build-packages:
      - libusb-1.0-0
      - swig
      - swig3.0
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libusb-1.0-0
      - libstdc++6
      - libc6
      - libudev1
      - libgcc1
      - libwebkit2gtk-4.0-37

