name: sathelperapp
version: git
version-script: cat version
summary: LRIT/HRIT Demodulator / Decoder
description: |
  The OpenSatelliteProject Satellite Helper Application! This is currently a LRIT/HRIT Demodulator / Decoder program

grade: devel
confinement: devmode

parts:
  ppaadd:
    plugin: nil
    override-build: |
      echo "deb http://ppa.launchpad.net/opensatelliteproject/ppa/ubuntu xenial main" | tee /etc/apt/sources.list.d/opensatelliteproject.list
      echo "deb http://ppa.launchpad.net/opensatelliteproject/drivers/ubuntu xenial main" | tee /etc/apt/sources.list.d/drivers.list
      echo "deb http://ppa.launchpad.net/gophers/archive/ubuntu xenial main" | tee /etc/apt/sources.list.d/gophers-archive.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 496DD3727263A7A279F9B349407E8BB01C195687
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 11FC2E68126782B43762694F22C627172ECB91FE
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C73998DC9DFEA6DCF1241057308C15A29AD198E9
      apt update
      apt install -yy  limesuite liblimesuite-dev libcorrect libsathelper libsoapysdr0.6 libairspy0 libsoapysdr-dev libairspy-dev libusb-1.0-0-dev golang-1.10
    prime: [-*]

  sathelperapp:
    source: .
    plugin: make
    after: [ppaadd]
    build-packages:
      - libusb-1.0-0
      - liblimesuite-dev
      - swig
      - swig3.0
    stage-packages:
      - libusb-1.0-0
      - libcorrect
      - libsathelper
      - libairspy0
      - libsoapysdr0.6
      - libstdc++6
      - soapysdr0.6-module-lms7
      - limesuite
      - libc6
      - libudev1
      - libgcc1

apps:
  sathelperapp:
    plugs: [network-bind, network, raw-usb]
    command: SatHelperApp
